package com.ev.Model;

public enum VillageNotificationType {
    ADMIN_APPROVAL,
    ADMIN_UPDATE,
    ACTIVITY_REQUEST_STATUS_CHANGE,
    USER_BOOKING,
    ACTIVITY_STARTED,
    ACTIVITY_ENDED,
    EVENT_STARTED,
    WEATHER_UNAVAILABLE,
    CUSTOM,
    BOOKING_CANCELLED,
    BOOKING_CLOSED
}
